### ISSUE TITLE
Use of Sanitizer::removeHTMLtags was deprecated in MediaWiki 1.38

### ISSUE THREAD

**Issue by DevarooGit** [Universal-Omega/SimpleTooltip#3]
Hello, thanks for maintaining this useful extension! Just wanted to let you know that use of Sanitizer::removeHTMLtags was apparently deprecated in MediaWiki 1.38. This is the message I get with a MW 1.39 installation:

> Deprecated: Use of Sanitizer::removeHTMLtags was deprecated in MediaWiki 1.38. [Called from SimpleTooltipHooks::inlineTooltip in ~/extensions/SimpleTooltip/src/SimpleTooltipHooks.php at line 43] in
> ~/includes/debug/MWDebug.php on line 381

Best regards,
Devaroo

**Comment by Universal-Omega** [comment]
Thank you for reporting this.

**Comment by DevarooGit** [comment]
Too easy. Thanks for fixing it ! Have a nice evening
